config/routes.rb
Blackboard::Application.routes.draw do
	# Index
  root "index#index"
  post "/login", to: "index#login", as: :login
  post "/logout", to: "index#logout", as: :logout
  post "/register", to: "index#register", as: :register
  # Write
  get "/write(/:day)", to: "write#write", as: :write
  put "/write/:day/update_title", to: "write#update_title", as: :update_title
  put "/write/:day/update_content", to: "write#update_content", as: :update_content
  get "/write/share/:day", to: "write#share", as: :share_document
  # Share
  get "/share/:user_id/:day", to: "share#share", as: :shared
end

app/controllers/write_controller.rb
class WriteController < ApplicationController
	before_action :require_login
	around_action :render_errors, only: [:update_title, :update_content]
	around_action :with_user_time_zone
	
	# Write for a given day, defaulting to the current day
	def write
		@day = post_params[:day] ? Day.from_identifier(post_params[:day]) : Day.from_time(Time.zone.now)
		@docs = Document.for_user(@user.id, @day.year, @day.month)
		@progress = Hash[*@docs.map { |doc| [Day.calculate_identifier(doc.year, doc.month, doc.day), (doc.words.to_f / doc.goal)] }.flatten]
		@document = get_or_create_document(@user, @day)
	end
	
	# Update the title for a single document
	def update_title
		day = Day.from_identifier(post_params[:day])
		document = Document.for_user(@user.id, day.year, day.month, day.day).first
		raise "Unknown document" unless document
		document.title = post_params[:title]
		document.save!
		render_ok
	end
	
	# Update the content for a single document
	def update_content
		day = Day.from_identifier(post_params[:day])
		document = Document.for_user(@user.id, day.year, day.month, day.day).first
		raise "Unknown document" unless document
		document.content = post_params[:content]
		document.words = count_words(post_params[:content])
		document.save!
		render_ok
	end
	
	# Toggles shareability for a single document
	def share
		day = Day.from_identifier(post_params[:day])
		document = Document.for_user(@user.id, day.year, day.month, day.day).first
		raise "Unknown document" unless document
		document.shared = !document.shared
		document.save!
		if document.shared
			redirect_to shared_path(@user.id, post_params[:day])
		else
			redirect_to write_path(post_params[:day])
		end
	end
	
	private
	
	def get_or_create_document(user, day)
		document = Document.for_user(user.id, day.year, day.month, day.day).first
		return document if document
		
		now = day.time.strftime("%A %B #{day.day.ordinalize}")
		Document.create(goal: user.goal, user_id: user.id, year: day.year, month: day.month, day: day.day, title: "Untitled Document (#{now})")
	end
	
	def count_words(content)
		content.split(/\s+/).count
	end
	
	def render_ok
		render nothing: true, status: 200
	end
	
	def post_params
		@post_params ||= params.permit(:title, :day, :content)
	end
end

app/helpers/write_helper.rb
module WriteHelper
	def day_classes(day, selected_day)
		now = Time.zone.now
		classes = ["calendar-day"]
		if day.day == now.day
			classes << "today"
		elsif day.day < now.day
			classes << "past"
		else
			classes << "future"
		end
		classes << "selected" if selected_day && selected_day.is?(day)
		classes.join(" ")
	end
end

app/views/write/write.html.erb
<% content_for :title, "Write" %>

<section id="write-title" class="grid">
	<div id="document-title" data-submit-path="<%= update_title_path(@day.identifier) %>" data-submit-name="title" class="col-8"><%= @document.title[0...50] %></div>
	<div id="document-words" class="col-4">
		<span id="document-words-current"><%= @document.words %></span> / <span id="document-words-goal"><%= @document.goal %></span> Words
	</div>
</section>

<textarea id="write-body" autofocus="autofocus" placeholder="Begin writing..." data-update-path="<%= update_content_path(@day.identifier) %>"><%= @document.content %></textarea>

<section id="navigation-bar">
	<div id="footer-display" class="grid">
		<div id="footer-left" class="col-6">
			<%= link_to fa_icon("chevron-left"), write_path(Day.from_time((@day.time - 1.month).change(day: 1)).identifier), class: "navigate left-arrow" if @day.pastable %>
			<span id="now-time"><%= link_to @day.time.strftime("%A %B #{@day.time.day.ordinalize} %Y"), write_path %></span>
			<%= link_to fa_icon("chevron-right"), write_path(Day.from_time((@day.time + 1.month).change(day: 1)).identifier), class: "navigate right-arrow" if @day.futureable %>
			<span id="save-display">Saved <span class="timestamp" data-livestamp="<%= @document.updated_at.to_i if @document %>"></span></span>
			<span id="share-display"><%= link_to @document.shared ? "Unshare" : "Share", share_document_path(@day.identifier) %></span>
		</div>
		<div id="footer-right" class="col-6">
			<span id="current-user"><%= @user.username %></span>
			<%= form_tag logout_path, id: "logout-form" do %>
				<%= button_tag :Logout %>
			<% end %>
		</div>
	</div>
	<nav id="month-bar">
		<table id="calendar">
			<tr>
				<% month = Month.new(@day.time) %>
				<% month.each_day do |day| %>
					<%= content_tag :td, data: { progress: @progress[day.identifier] || 0 }, class: day_classes(day, @day), style: "width:#{100.0 / month.num_days}%" do %>
						<%= link_to day.day, write_path(day.identifier) %>
					<% end %>
				<% end %>
			</tr>
		</table>
	</nav>
</section>